### ISSUE TITLE
JSON parse error: Vim(return):E117: Unknown function: js_decode

### ISSUE THREAD

**Issue by fantoro** [twitvim/twitvim#19]
Hey, everything seems to work but I keep getting these `js_decode` errors.

**Comment by mattn** [comment]
What version of vim do you use?

**Comment by fantoro** [comment]
I use NeoVim v0.3.7

**Comment by mattn** [comment]
I'm not familier to neovim. Neovim does not have js_decode?

**Comment by mattn** [comment]
Anyway, I added check js_decode. Thank you.
