### ISSUE TITLE
2 Small Fixes required to use :SetLoginTwitter

### ISSUE THREAD

**Issue by tjharman** [twitvim/twitvim#5]
Hi,

I just installed vim8.0 on my windows box and I had to make a couple of small changes to **TwitVim v0.9.1** to get it to work.  I'm useless at git, so I haven't submitted a push/pull/thingus request because, well, I don't understand how to do that.

Please note that I'm using only OpenSSL and Curl here.  This bug report might not apply to people using the Perl/Ruby etc path.

The first change I had to made was the is.gd URL shortener now give a 302 if you try to access it using http.  It must be accessed via https.

Line 4707 of autoload/twitvim.vim must be changed to
`let url = 'https://is.gd/api.php?longurl='.s:url_encode(a:url)`

Next and the more important fix is that the latest version of Curl I downloaded for Windows (and I suspect would be included with recent Ubuntu's etc) will happily talk http2 if supported, which Twitter does.  But this returns a bunch of binary garbage that TwitVim didn't understand.  To fix that, I had to edit line 1153 to read:

`let curlcmd = "curl --http1.1 -s -S "`

This forces the use of http1.1 which then let me sign into TwitVim correctly and it's now working a treat.

I hope this is a useful bug report, please let me know if I can offer anything else.

**Comment by mattn** [comment]
The second is already merged in https://github.com/twitvim/twitvim/commit/aaca4a244edd9579358ba389dc7af279dbe4463e

**Comment by tjharman** [comment]
Apologies, I think to troubleshoot I went back from the git version to the version on the vim website.
Hopefully the is.gd fix is useful.

**Comment by mattn** [comment]
I you still have an issue, please reopen this. Thanks

**Comment by mattn** [comment]
Ah, concurrent comments. Were you okay to close?

**Comment by tjharman** [comment]
Yup, I see you've merged the is.gd fix too. Please close.
