### ISSUE TITLE
Authorization required 401

### ISSUE THREAD

**Issue by horse-latitudes** [twitvim/twitvim#9]
Hi. I've installed twitvim via Vundle & followed the help files & authorized the app with Twitter & entered the PIN number in Vim but now when I try to post I get:

`Error posting your tweet: 401 Authorization Required`

The token is in $HOME & has the right username. I've Googled this but no luck.
Any help appreciated. Cheers Phil.

**Comment by horse-latitudes** [comment]
I forgot to mention: just before the error message, Vim tells me I'm logged in with the correct Twitter username. Then it errors. I'm using:

`:CPosttoTwitter`

as a test to see if it works...

**Comment by mattn** [comment]
Are you using 2FA?

**Comment by horse-latitudes** [comment]
no. Should I enable it on Twitter?

**Comment by mattn** [comment]
No, not required. Could you please try again with removing `~/.twitvim.token` ?

**Comment by horse-latitudes** [comment]
I did as you asked then entered the new PIN number that Twitter asked for but unfortunately that resulted in the same 401 message as before when I tried to post.

**Comment by mattn** [comment]
If you are asked PIN number, you already enabled 2FA. Maybe PIN number is recieved on your mobile phone.

**Comment by horse-latitudes** [comment]
no the PIN came via a web browser. I've looked at my Twitter settings & 2FA is not enabled.

**Comment by mattn** [comment]
PIN code doesn't came via web browser since because github doesn't provide the way.
>I've looked at my Twitter settings & 2FA is not enabled.

No, GitHub 2FA.

**Comment by mattn** [comment]
Please look at https://github.com/settings/security

**Comment by horse-latitudes** [comment]
yes I have GitHub 2FA enabled. I'm confused. Why would GitHub 2FA be of importance when communicating between Vim & Twitter?

**Comment by mattn** [comment]
Ah, I'm sorry. I was confused. Maybe I'm sleepy.
Yes, It's OAuth on twitter not 2FA. You can see the PIN code. But if you didn't login same user as user which you logged in with twitvim, you don't see the number. Once logout please.

**Comment by horse-latitudes** [comment]
logout of what? I'm sorry I don't understand

**Comment by mattn** [comment]
If your account which try to logged-in with twitvim is not same as account which already logged-in on browser, you should logged-out at once.

So try this.

1. Logged out with browser.
2. Logged in with browser again.
3. Logged in with twitvim.

If you see prompt for PIN code in your terminal, also you will see the URL to open browser. Then, please open the URL.

**Comment by horse-latitudes** [comment]
still no good. Still get 401 code.
Twitter recognises me as logged in to the correct account but then stalls & throws the error.

**Comment by mattn** [comment]
Do you use http proxy? And what you see with `:echo twitvim#show_curl_method()` ?

**Comment by horse-latitudes** [comment]
the echo command shows:

`Net Method: perl
0`

& I'm not using a proxy

**Comment by mattn** [comment]
Do you set `g:twitvim_enable_perl` to 1?

**Comment by horse-latitudes** [comment]
I have it set to:

`let twitvim_enable_perl = 1`

because using your setting above causes Vim to error

**Comment by mattn** [comment]
If you have curl command, you don't need to set.

**Comment by horse-latitudes** [comment]
I commented out the enable perl line & it worked first time.
Good stuff. Thanks for all your help.
